name: CI

on: [pull_request]

jobs:
  test:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
    - name: Set required PowerShell modules
      id: psmodulecache
      uses: potatoqualitee/psmodulecache@v1
      with:
        modules-to-cache: Requirements:2.3.6, Pester:4.10.1
    - name: Setup PowerShell module cache
      id: cacher
      uses: actions/cache@v2
      with:
          path: ${{ steps.psmodulecache.outputs.modulepath }}
          key: ${{ runner.os }}-${{ steps.psmodulecache.outputs.keygen }}
    - name: Install required PowerShell modules
      if: steps.cacher.outputs.cache-hit != 'true'
      shell: pwsh
      run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          $modulelist = "${{ steps.psmodulecache.inputs.modules-to-cache }}"
          $modules = $modulelist.Split(',').Trim()
          foreach ($module in $modules) {
            $name, $version = $module.Split(':')
            Install-Module -Name $name -RequiredVersion $version -ErrorAction Stop
          }
    - name: Run Build Script
      shell: pwsh
      run: |
      Import-Module Requirements
      .\build.ps1
    - name: Upload module artifact
      uses: actions/upload-artifact@v2
      with:
        name: signalfx-module
        path: release/
