name: CI

on: [pull_request]

jobs:
  test:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    
    steps:
    - uses: actions/checkout@v1
    - name: Install Requirements
      run: Install-Module Requirements -RequiredVersion 2.3.6 -Force -SkipPublisherCheck
      shell: pwsh
    - name: Run Build Script
      run: .\build.ps1
      shell: pwsh
